In [1]:
import numpy as  np
x=np.array([[0.1,0.5],
            [1.1,2.3],
            [-1.1,-2.3],
            [-1.5,-2.5]])
w=np.array([[0.1,.2,0.3],
            [0.1,0.2,0.3]])

bias=np.array([[0.01,0.1,0.1]])

print(x)
print(w)
print(bias)

[[ 0.1  0.5]
 [ 1.1  2.3]
 [-1.1 -2.3]
 [-1.5 -2.5]]
[[0.1 0.2 0.3]
 [0.1 0.2 0.3]]
[[0.01 0.1  0.1 ]]


In [2]:
def net_input(x,w,b):
  return(x.dot(w)+b)
net_in=net_input(x,w,bias)
print(net_in)


[[ 0.07  0.22  0.28]
 [ 0.35  0.78  1.12]
 [-0.33 -0.58 -0.92]
 [-0.39 -0.7  -1.1 ]]


In [3]:
def softmax(net_in):
  return(np.exp(net_in)/np.sum(np.exp(net_in)))
softmax_out=softmax(net_in)
print(softmax_out)

[[0.07949827 0.09236381 0.09807527]
 [0.10518653 0.16169878 0.22717831]
 [0.05328928 0.04150173 0.0295397 ]
 [0.05018596 0.03680874 0.02467363]]


In [4]:
def to_classlable(z):
  return(z.argmax(axis=1))
classlable=to_classlable(softmax_out)
print(classlable)

[2 2 0 0]
