In [1]:
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import animation
import cv2


# **Example 1**

# **Step 1 3X3 kernal**

In [3]:
inp=np.array(([4,5,8,7],[1,8,8,8],[3,6,6,4],[6,5,7,5]))
print(inp.shape)
inp

(4, 4)


array([[4, 5, 8, 7],
       [1, 8, 8, 8],
       [3, 6, 6, 4],
       [6, 5, 7, 5]])

# **Step 2 Kernal filter**

In [8]:
k=np.array(([1,4,-1],[1,3,3],[1,0,-2]))
print(k.shape)
k

(3, 3)


array([[ 1,  4, -1],
       [ 1,  3,  3],
       [ 1,  0, -2]])

# **Step 3 creating conv Matrix**

In [11]:
w,h=inp.shape
kw,kh=k.shape
s=1
w_o=int((w-kw)/s)+1
h_o=int((h-kh)/s)+1

ext_mat=np.zeros((w*h))
for i in range(kw):
  ext_mat[i*h:i*h+kh]=k[i]
print(ext_mat)
print(ext_mat.shape)

[ 1.  4. -1.  0.  1.  3.  3.  0.  1.  0. -2.  0.  0.  0.  0.  0.]
(16,)


In [12]:
ext_ker=[]
for i in range(w_o):
  for j in range(h_o):
    ext_mat1=np.roll(ext_mat,h*i*s+j*s)
    ext_ker.append(ext_mat1)
ext_ker=np.array(ext_ker)
print('Conv Matrix')
print(ext_ker.shape)
print(ext_ker)


Conv Matrix
(4, 16)
[[ 1.  4. -1.  0.  1.  3.  3.  0.  1.  0. -2.  0.  0.  0.  0.  0.]
 [ 0.  1.  4. -1.  0.  1.  3.  3.  0.  1.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  4. -1.  0.  1.  3.  3.  0.  1.  0. -2.  0.]
 [ 0.  0.  0.  0.  0.  1.  4. -1.  0.  1.  3.  3.  0.  1.  0. -2.]]


# **Step 4 Conv feature map**

In [13]:
#converting inp image to column vector
inp=inp.flatten()

#convolution
out=np.matmul(ext_ker,inp)
out=np.reshape(out,(w_o,h_o))
print('Conv Feature Map')
print(out)
print(out.shape)


Conv Feature Map
[[56. 84.]
 [56. 63.]]
(2, 2)


# **Step 5  unsampling using transposed conv**

In [14]:
w,h=out.shape
wk,hk=k.shape
s=1
w_o=int(((w-1)*s)+wk)
h_o=int(((h-1)*s)+hk)
inp=out.flatten()

out=np.matmul(ext_ker.T,inp)
out=np.reshape(out,(w_o,h_o))
print('Unsampling')
print(out)
print(out.shape)

Unsampling
[[  56.  308.  280.  -84.]
 [ 112.  539.  616.  189.]
 [ 112.  315.  245.   21.]
 [  56.   63. -112. -126.]]
(4, 4)


# **Example 2**

In [29]:
inp=np.array(([4,5,8,7,6,7],[1,8,8,8,3,5],[3,6,6,4,5,7],[6,5,7,5,9,2],[1,2,3,4,5,6],[9,7,5,8,6,3]))
print(inp.shape)
inp

(6, 6)


array([[4, 5, 8, 7, 6, 7],
       [1, 8, 8, 8, 3, 5],
       [3, 6, 6, 4, 5, 7],
       [6, 5, 7, 5, 9, 2],
       [1, 2, 3, 4, 5, 6],
       [9, 7, 5, 8, 6, 3]])

In [30]:
k=np.array(([1,4,-1],[1,3,3],[1,0,-2]))
print(k.shape)
k

(3, 3)


array([[ 1,  4, -1],
       [ 1,  3,  3],
       [ 1,  0, -2]])

In [31]:
w,h=inp.shape
kw,kh=k.shape
s=1
w_o=int((w-kw)/s)+1
h_o=int((h-kh)/s)+1

ext_mat=np.zeros((w*h))
for i in range(kw):
  ext_mat[i*h:i*h+kh]=k[i]
print(ext_mat)
print(ext_mat.shape)

[ 1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.  1.  0. -2.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
(36,)


In [24]:
ext_ker=[]
for i in range(w_o):
  for j in range(h_o):
    ext_mat1=np.roll(ext_mat,h*i*s+j*s)
    ext_ker.append(ext_mat1)
ext_ker=np.array(ext_ker)
print('Conv Matrix')
print(ext_ker.shape)
print(ext_ker)


Conv Matrix
(16, 36)
[[ 1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.  1.  0. -2.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.  1.  0. -2.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.  1.  0. -2.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.  1.  0. -2.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.  0.
   1.  0. -2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.  0.
   0.  1.  0. -2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  4. -1.  0.  0.  0.  1.  3.  3.  0.
   0.  0.  

In [25]:
#converting inp image to column vector
inp=inp.flatten()

#convolution
out=np.matmul(ext_ker,inp)
out=np.reshape(out,(w_o,h_o))
print('Conv Feature Map')
print(out)
print(out.shape)


Conv Feature Map
[[56. 84. 67. 46.]
 [56. 63. 59. 56.]
 [58. 61. 59. 47.]
 [34. 42. 41. 78.]]
(4, 4)


In [26]:
w,h=out.shape
wk,hk=k.shape
s=1
w_o=int(((w-1)*s)+wk)
h_o=int(((h-1)*s)+hk)
inp=out.flatten()

out=np.matmul(ext_ker.T,inp)
out=np.reshape(out,(w_o,h_o))
print('Unsampling')
print(out)
print(out.shape)

Unsampling
[[  56.  308.  347.  230.  117.  -46.]
 [ 112.  539.  742.  728.  504.   82.]
 [ 170.  608.  616.  522.  340.   29.]
 [ 148.  476.  538.  537.  471.  -49.]
 [  92.  205.  212.  252.  239.  140.]
 [  34.   42.  -27.   -6.  -82. -156.]]
(6, 6)


Do kernal for 5x5 and 1x1 same procedure keep array 6x6